[package]
name = "gomoku_game_websocket"
version = "0.1.0"
authors = ["EricJeffrey <1719937412@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.2"
